language: swift
osx_image: xcode10.2
script:
    - xcodebuild -scheme Quiver -project Quiver.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=11.3' build test
after_success:
    - bash <(curl -s https://codecov.io/bash) -J 'Quiver'
